name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
    paths:
      - "web_scraper_service/**"
      - "data_ingestion_service/**"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  test-web-scraper:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_scraper_service

    services:
      kafka:
        image: bitnami/kafka:latest
        env:
          KAFKA_CFG_NODE_ID: 0
          KAFKA_CFG_PROCESS_ROLES: 'controller,broker'
          KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
          KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
          KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
          KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '0@kafka:9093'
          KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
          ALLOW_PLAINTEXT_LISTENER: 'yes'
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
        ports:
          - 9092:9092

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Wait for Kafka to start
        run: sleep 20

      - name: Run Web Scraper Tests
        run: python run_tests.py
        env:
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092

  test-data-ingestion:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data_ingestion_service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Data Ingestion Tests
        run: python run_tests.py